name: Build and push to GHCR
on:
  push:
    branches:
      - main
jobs:
  push_to_ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and tag image
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker build --tag ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:$COMMIT_SHA .
